import {
  Project,
  Deliverable,
  DocumentItem,
  MeetingItem,
  ExecutiveDashboardData,
  ActivityLogItem,
  Profile,
} from '~/types';

export const mockCurrentUser: Profile = {
  id: 'user-001',
  email: 'den.director@tsri.or.th',
  full_name: 'ดร.เด่นชัย ปัญญาไว (ผู้อำนวยการโครงการ)',
  organization: 'สำนักงานคณะกรรมการส่งเสริมวิทยาศาสตร์ วิจัยและนวัตกรรม (สกสว.)',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
};

export const mockProject: Project = {
  id: 'proj-tsri-2026-01',
  code: 'TSRI-LEGAL-2026',
  title: 'โครงการศึกษา วิเคราะห์ และพัฒนาองค์ความรู้ด้านกฎหมาย ระเบียบ และแนวปฏิบัติที่เกี่ยวข้องกับการดำเนินงานของ สกสว.',
  description: 'โครงการพัฒนาระบบบริหารความรู้และควบคุมการปฏิบัติตามกฎหมาย นโยบาย ววน. และระเบียบ สกสว. ครบวงจร',
  organization: 'สำนักงานคณะกรรมการส่งเสริมวิทยาศาสตร์ วิจัยและนวัตกรรม (สกสว.)',
  current_gate: 'G2', // G2: Research Validation
  start_date: '2026-01-15',
  end_date: '2026-10-31',
  baseline_budget: 4500000,
  created_at: '2026-01-10T08:00:00Z',
};

export const mockDeliverables: Deliverable[] = [
  {
    id: 'del-01',
    project_id: mockProject.id,
    code: 'DEL-01',
    title: 'รายงานการวิเคราะห์และรวบรวมบทบัญญัติกฎหมาย ระเบียบ และคำสั่งที่เกี่ยวข้องกับ สกสว. (Inception Report)',
    description: 'รวบรวม พ.ร.บ. สภานโยบายฯ พ.ศ. 2562 และระเบียบกองทุน ววน. ครบถ้วน',
    weight_percentage: 20,
    due_date: '2026-03-31',
    gate_milestone: 'G1',
    status: 'APPROVED',
  },
  {
    id: 'del-02',
    project_id: mockProject.id,
    code: 'DEL-02',
    title: 'รายงานการวิเคราะห์ช่องว่าง (Legal & Operational Gap Analysis) และผลกระทบต่อภารกิจ',
    description: 'วิเคราะห์ความสอดคล้องระหว่างอำนาจหน้าที่ตามกฎหมายกับกระบวนการทำงานจริง',
    weight_percentage: 25,
    due_date: '2026-05-31',
    gate_milestone: 'G3',
    status: 'IN_PROGRESS',
  },
  {
    id: 'del-03',
    project_id: mockProject.id,
    code: 'DEL-03',
    title: 'ร่างคู่มือและแนวปฏิบัติการดำเนินงานตามกฎหมายระเบียบใหม่ (Standard Operating Procedure Guide)',
    description: 'จัดทำร่างคู่มือ SOP พร้อม Flowchart สำหรับหน่วยงานภายใน สกสว.',
    weight_percentage: 25,
    due_date: '2026-07-31',
    gate_milestone: 'G4',
    status: 'BACKLOG',
  },
  {
    id: 'del-04',
    project_id: mockProject.id,
    code: 'DEL-04',
    title: 'ชุดองค์ความรู้และระบบ Legal Traceability Explorer ฉบับสมบูรณ์',
    description: 'ระบบสืบค้นความเชื่อมโยงของบทบัญญัติ สิทธิ หน้าที่ และเอกสารหลักฐาน',
    weight_percentage: 30,
    due_date: '2026-09-30',
    gate_milestone: 'G5',
    status: 'BACKLOG',
  },
];

export const mockDocuments: DocumentItem[] = [
  {
    id: 'doc-001',
    project_id: mockProject.id,
    prefix_code: 'LAW',
    document_code: 'LAW-001',
    title: 'พระราชบัญญัติการส่งเสริมวิทยาศาสตร์ วิจัยและนวัตกรรม พ.ศ. 2562',
    category: 'กฎหมายจัดตั้งและอำนาจหน้าที่',
    issuing_body: 'ราชกิจจานุเบกษา',
    effective_date: '2019-05-02',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['กฎหมายหลัก', 'อำนาจหน้าที่', 'ววน.'],
    is_confidential: false,
    created_at: '2026-01-20T09:00:00Z',
    updated_at: '2026-01-20T09:00:00Z',
    versions: [
      {
        id: 'ver-001-1',
        document_id: 'doc-001',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'TSRI_Act_2562_Full.pdf',
        file_size_bytes: 3450000,
        file_mime_type: 'application/pdf',
        storage_r2_key: 'laws/2026/TSRI_Act_2562_Full.pdf',
        change_summary: 'ฉบับประกาศราชกิจจานุเบกษา ตรวจสอบเทียบตัวบทสมบูรณ์',
        status: 'VALIDATED',
        validated_at: '2026-01-22T10:00:00Z',
        created_at: '2026-01-20T09:00:00Z',
      },
    ],
  },
  {
    id: 'doc-002',
    project_id: mockProject.id,
    prefix_code: 'REG',
    document_code: 'REG-004',
    title: 'ระเบียบคณะกรรมการส่งเสริม ววน. ว่าด้วยการบริหารเงินกองทุนส่งเสริม ววน. พ.ศ. 2563',
    category: 'การเงินและพัสดุ',
    issuing_body: 'คณะกรรมการส่งเสริม ววน.',
    effective_date: '2020-03-15',
    status: 'VALIDATED',
    latest_version_number: '1.1',
    tags: ['การเงิน', 'กองทุน ววน.', 'ระเบียบปฏิบัติ'],
    is_confidential: false,
    created_at: '2026-01-25T11:00:00Z',
    updated_at: '2026-02-10T14:30:00Z',
    versions: [
      {
        id: 'ver-002-2',
        document_id: 'doc-002',
        project_id: mockProject.id,
        version_number: '1.1',
        file_name: 'Fund_Regulation_2563_Rev1.pdf',
        file_size_bytes: 1820000,
        file_mime_type: 'application/pdf',
        storage_r2_key: 'regulations/Fund_Regulation_2563_Rev1.pdf',
        change_summary: 'ปรับปรุงตามประกาศฉบับแก้ไขเพิ่มเติมปี 2565',
        status: 'VALIDATED',
        validated_at: '2026-02-10T15:00:00Z',
        created_at: '2026-02-10T14:30:00Z',
      },
      {
        id: 'ver-002-1',
        document_id: 'doc-002',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'Fund_Regulation_2563_Original.pdf',
        file_size_bytes: 1750000,
        file_mime_type: 'application/pdf',
        storage_r2_key: 'regulations/Fund_Regulation_2563_Original.pdf',
        change_summary: 'ฉบับแรกเริ่มปี 2563',
        status: 'SUPERSEDED',
        created_at: '2026-01-25T11:00:00Z',
      },
    ],
  },
  {
    id: 'doc-003',
    project_id: mockProject.id,
    prefix_code: 'TOR',
    document_code: 'TOR-01',
    title: 'เอกสารข้อกำหนดของโครงการ (Terms of Reference) ฉบับอนุมัติ',
    category: 'สัญญาและกรอบโครงการ',
    issuing_body: 'สกสว.',
    effective_date: '2026-01-15',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['TOR', 'สัญญางาน', 'Baseline'],
    is_confidential: true,
    created_at: '2026-01-15T08:30:00Z',
    updated_at: '2026-01-15T08:30:00Z',
    versions: [
      {
        id: 'ver-003-1',
        document_id: 'doc-003',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'TSRI_Legal_Project_TOR_Final.pdf',
        file_size_bytes: 4200000,
        file_mime_type: 'application/pdf',
        storage_r2_key: 'tor/TSRI_Legal_Project_TOR_Final.pdf',
        change_summary: 'ฉบับลงนามในสัญญาจ้าง',
        status: 'VALIDATED',
        validated_at: '2026-01-15T10:00:00Z',
        created_at: '2026-01-15T08:30:00Z',
      },
    ],
  },
  {
    id: 'doc-004',
    project_id: mockProject.id,
    prefix_code: 'REP',
    document_code: 'REP-02',
    title: 'ร่างรายงานผลการวิเคราะห์ช่องว่างทางกฎหมายและแนวปฏิบัติ (Draft Gap Analysis Report)',
    category: 'รายงานวิจัยและวิเคราะห์',
    issuing_body: 'คณะนักวิจัยโครงการ',
    status: 'UNDER_REVIEW',
    latest_version_number: '0.9',
    tags: ['Gap Analysis', 'ผลการวิเคราะห์', 'รอตรวจ'],
    is_confidential: true,
    created_at: '2026-09-18T16:00:00Z',
    updated_at: '2026-09-20T11:20:00Z',
    versions: [
      {
        id: 'ver-004-1',
        document_id: 'doc-004',
        project_id: mockProject.id,
        version_number: '0.9',
        file_name: 'TSRI_Gap_Analysis_Report_v0.9.docx',
        file_size_bytes: 8650000,
        file_mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        storage_r2_key: 'reports/TSRI_Gap_Analysis_Report_v0.9.docx',
        change_summary: 'ร่างรายงานฉบับแรกส่งให้ที่ปรึกษากฎหมายและ PM ตรวจสอบ',
        status: 'UNDER_REVIEW',
        created_at: '2026-09-20T11:20:00Z',
      },
    ],
  },
  {
    id: 'doc-005',
    project_id: mockProject.id,
    prefix_code: 'MOM',
    document_code: 'MOM-2026-04',
    title: 'บันทึกการประชุมคณะทำงานวิจัยกฎหมาย สกสว. ครั้งที่ 4/2569',
    category: 'บันทึกการประชุม',
    issuing_body: 'คณะทำงานโครงการ',
    status: 'VERIFIED',
    latest_version_number: '1.0',
    tags: ['การประชุม', 'MOM', 'คณะทำงาน'],
    is_confidential: false,
    created_at: '2026-09-10T17:00:00Z',
    updated_at: '2026-09-12T09:00:00Z',
    versions: [
      {
        id: 'ver-005-1',
        document_id: 'doc-005',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'MOM_Meeting_04_2026.pdf',
        file_size_bytes: 1250000,
        file_mime_type: 'application/pdf',
        storage_r2_key: 'mom/MOM_Meeting_04_2026.pdf',
        change_summary: 'บันทึกการประชุมรับรองมติเรื่องกรอบการวิเคราะห์ Mandate',
        status: 'VERIFIED',
        created_at: '2026-09-10T17:00:00Z',
      },
    ],
  },
];

export const mockMeetings: MeetingItem[] = [
  {
    id: 'meet-001',
    project_id: mockProject.id,
    meeting_number: 'MTG-2026-05',
    title: 'ประชุมพิจารณาร่างรายงาน Gap Analysis ร่วมกับฝ่ายกฎหมายและ HRD สกสว.',
    agenda: '1. สรุปผลการสังเคราะห์กฎหมาย 14 ฉบับ\n2. พิจารณาประเด็นช่องว่างในกระบวนการจัดสรรงบประมาณ\n3. กำหนดวันลงพื้นที่สัมภาษณ์ผู้บริหาร',
    meeting_type: 'ประชุมผู้เชี่ยวชาญ & ผู้มีส่วนได้ส่วนเสีย',
    gate_ref: 'G2',
    scheduled_at: '2026-09-25T13:30:00Z',
    duration_minutes: 150,
    location_or_link: 'ห้องประชุม 501 สกสว. และ Zoom Cloud Meeting',
    status: 'SCHEDULED',
    attendees_count: 12,
  },
  {
    id: 'meet-002',
    project_id: mockProject.id,
    meeting_number: 'MTG-2026-06',
    title: 'ประชุมกลั่นกรอง Gate G3 (Analysis Validation Readiness)',
    agenda: 'ตรวจสอบความพร้อมของผลการวิเคราะห์ก่อนเข้าสู่การจัดทำร่างคู่มือ SOP',
    meeting_type: 'Gate Review',
    gate_ref: 'G3',
    scheduled_at: '2026-10-08T09:30:00Z',
    duration_minutes: 120,
    location_or_link: 'Microsoft Teams Link',
    status: 'SCHEDULED',
    attendees_count: 8,
  },
];

export const mockActivities: ActivityLogItem[] = [
  {
    id: 'act-001',
    project_id: mockProject.id,
    actor_name: 'ดร.เด่นชัย ปัญญาไว',
    action: 'UPLOAD_VERSION',
    entity_table: 'document_versions',
    entity_id: 'ver-004-1',
    description: 'อัปโหลดเอกสารร่างรายงาน Gap Analysis (REP-02 v0.9)',
    created_at: '2026-09-20T11:20:00Z',
  },
  {
    id: 'act-002',
    project_id: mockProject.id,
    actor_name: 'นายกฤษฎา นิติธรรม (ที่ปรึกษากฎหมาย)',
    action: 'VALIDATE_DOCUMENT',
    entity_table: 'documents',
    entity_id: 'doc-002',
    description: 'รับรองความถูกต้องของเอกสารระเบียบการเงิน (REG-004 v1.1)',
    created_at: '2026-09-19T15:00:00Z',
  },
  {
    id: 'act-003',
    project_id: mockProject.id,
    actor_name: 'น.ส.ภัทรวดี จัดการงาน (PM)',
    action: 'SCHEDULE_MEETING',
    entity_table: 'meetings',
    entity_id: 'meet-001',
    description: 'กำหนดนัดหมายการประชุมพิจารณาร่าง Gap Analysis (MTG-2026-05)',
    created_at: '2026-09-18T14:15:00Z',
  },
];

export const mockDashboardData: ExecutiveDashboardData = {
  project: mockProject,
  currentGate: 'G2',
  torCoveragePercentage: 45,
  deliverablesProgress: {
    total: 4,
    completed: 1,
    inProgress: 1,
    pendingReview: 2,
  },
  pendingReviewsCount: 3,
  evidenceGapCount: 2,
  upcomingMeetings: mockMeetings,
  openRisksCount: 1,
  openDecisionsCount: 4,
  myActionItems: [
    {
      id: 'act-1',
      title: 'ตรวจทานความถูกต้องของบทบัญญัติในร่าง Gap Analysis (REP-02)',
      type: 'REVIEW',
      due_date: '2026-09-24',
      priority: 'HIGH',
    },
    {
      id: 'act-2',
      title: 'เตรียมสไลด์นำเสนอสำหรับการประชุม Gate G2 Review',
      type: 'MEETING',
      due_date: '2026-09-25',
      priority: 'MEDIUM',
    },
    {
      id: 'act-3',
      title: 'ขอรับรองความถูกต้องเอกสารคำสั่งมอบอำนาจ (ORD-012)',
      type: 'TASK',
      due_date: '2026-09-28',
      priority: 'LOW',
    },
  ],
  recentDocuments: mockDocuments,
  recentActivities: mockActivities,
};
