import {
  Project,
  Deliverable,
  DocumentItem,
  MeetingItem,
  ExecutiveDashboardData,
  ActivityLogItem,
  Profile,
  TeamMemberDetails,
  ReviewBatch,
  ReviewItem,
  ReviewEvidenceRecord,
  VerificationStatus,
} from '~/types';

export const mockCurrentUser: Profile = {
  id: 'usr-super-admin-01',
  email: 'dencapvision@gmail.com',
  full_name: 'นายอนุสรณ์ หนองนา (เด่น)',
  nickname: 'เด่น',
  role_title: 'Super Admin / ผู้จัดการโครงการ (PM & Learning Architect Lead)',
  organization: 'สำนักงานคณะกรรมการส่งเสริมวิทยาศาสตร์ วิจัยและนวัตกรรม (สกสว.)',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
};

export const mockTeamMembers: TeamMemberDetails[] = [
  // 1. ทีมบริหารโครงการ (Project Management Core Team)
  {
    id: 'pm-02',
    name: 'นายอนุสรณ์ หนองนา',
    nickname: 'เด่น',
    roleTitle: 'Super Admin / ผู้จัดการโครงการ (PM & Learning Architect Lead)',
    teamCategory: 'CORE_PM',
    teamCategoryName: '1. ทีมบริหารโครงการ (Project Management Core Team)',
    organization: 'ทีมบริหารโครงการ สกสว.',
    email: 'dencapvision@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    expertise: 'Super Admin, Project Cadence, Knowledge Translation, Learning Architecture, Master Facilitation',
    strategicFit: 'Super Admin และผู้นำการขับเคลื่อนกระบวนการทำงาน การแปลงองค์ความรู้กฎหมายสู่สื่อการเรียนรู้ และกระบวนการประชุมแบบมีส่วนร่วม',
    mainResponsibilities: [
      'ผู้ดูแลระบบระดับสูงสุด (Super Admin) ควบคุมความปลอดภัยและสิทธิ์เข้าถึงทั้งหมด',
      'บริหารโครงการภาพรวม (Project Execution & Cadence)',
      'แปลงองค์ความรู้สู่นวัตกรรมการเรียนรู้ (Knowledge Translation)',
      'อำนวยการประชุม (Master Facilitator)',
      'บูรณาการข้อคิดเห็นของที่ปรึกษาทุกท่าน สู่การจัดทำรายละเอียดชิ้นงานตาม TOR',
    ],
    specificConsultingTopics: [
      'การออกแบบระบบ Knowledge Management และ Platform สกสว.',
      'การวางสถาปัตยกรรมการเรียนรู้ Legal Competency',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-03', 'DEL-04'],
  },
  {
    id: 'pm-01',
    name: 'คุณไกรพุฒิ อินทรโยธา',
    nickname: 'ไนท์',
    roleTitle: 'ผู้จัดการโครงการ (Project Director & Strategic Risk Lead)',
    teamCategory: 'CORE_PM',
    teamCategoryName: '1. ทีมบริหารโครงการ (Project Management Core Team)',
    organization: 'ทีมบริหารโครงการ สกสว.',
    email: 'kraiput.night@tsri-project.org',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    expertise: 'ยุทธศาสตร์โครงการ, การบริหารความเสี่ยงเชิงกลยุทธ์, การบริหารสัญญางานวิจัย',
    strategicFit: 'ผู้นำเชิงยุทธศาสตร์ กำกับภาพรวมโครงการและประสานนโยบายระดับสูงกับ สกสว.',
    mainResponsibilities: [
      'รับผิดชอบภาพรวมโครงการฯ และทีมที่ปรึกษาทั้งหมด',
      'รวบรวมประเด็นความต้องการเชิงลึกจาก สกสว.',
      'ควบคุมรายละเอียดการส่งมอบงานตาม TOR ให้ครบถ้วน 100%',
    ],
    specificConsultingTopics: [
      'Strategic Alignment กับผู้บริหารระดับสูง สกสว.',
      'การบริหารจัดการความเสี่ยงของสัญญาและผลผลิต',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-03', 'DEL-04'],
  },
  {
    id: 'pm-03',
    name: 'ดร.หนึ่งนิดา สารศรี',
    nickname: 'ต้นหลิว',
    roleTitle: 'Co-PM (Research & Qualitative Process Specialist)',
    teamCategory: 'CORE_PM',
    teamCategoryName: '1. ทีมบริหารโครงการ (Project Management Core Team)',
    organization: 'ทีมบริหารโครงการ สกสว.',
    email: 'nuengnida.tonliw@tsri-project.org',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    expertise: 'ระเบียบวิธีวิจัยเชิงคุณภาพ, In-depth Interview, Focus Group, การวิเคราะห์ข้อมูลเชิงประจักษ์',
    strategicFit: 'ผู้เชี่ยวชาญกระบวนการวิจัยเชิงคุณภาพ ควบคุมมาตรฐานทางวิชาการและเครื่องมือเก็บข้อมูลภาคสนาม',
    mainResponsibilities: [
      'กำกับระเบียบวิธีวิจัยเชิงคุณภาพ',
      'ออกแบบและดำเนินการสัมภาษณ์เชิงลึก / Focus Group',
      'การวิเคราะห์ข้อมูลเชิงประจักษ์ และการสังเคราะห์รายงานวิจัย',
      'ร่วมทำรายงานข้อเสนอแนะ 3 ชุด เพื่อส่งมอบตาม TOR',
    ],
    specificConsultingTopics: [
      'การออกแบบชุดคำถามสัมภาษณ์เชิงลึกระดับบอร์ดและผู้บริหาร',
      'การสังเคราะห์ Gap Analysis รายงานข้อเสนอแนะ 3 เล่ม',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-04'],
  },
  {
    id: 'pm-04',
    name: 'คุณเบนซ์',
    nickname: 'เบนซ์',
    roleTitle: 'ผู้ประสานงานโครงการ (Project Coordinator)',
    teamCategory: 'CORE_PM',
    teamCategoryName: '1. ทีมบริหารโครงการ (Project Management Core Team)',
    organization: 'ทีมบริหารโครงการ สกสว.',
    email: 'benz.coordinator@tsri-project.org',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    expertise: 'การประสานงานโครงการ, Deliverables Tracking, งานธุรการและการนัดหมาย',
    strategicFit: 'ศูนย์กลางการติดต่อสื่อสารและการประสานงานระหว่างคณะที่ปรึกษากับ สกสว.',
    mainResponsibilities: [
      'การบริหารจัดการนัดหมายการประชุมและสัมภาษณ์',
      'ติดตามผลผลิต (Deliverables Tracking)',
      'งานธุรการโครงการและจัดเตรียมเอกสารการประชุม',
      'การประสานงานระหว่างคณะที่ปรึกษากับ สกสว.',
    ],
    specificConsultingTopics: [
      'ตารางการนัดหมาย Focus Group และการลงพื้นที่',
      'การรวบรวมเอกสารและการจัดทำบันทึก MOM',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-03', 'DEL-04'],
  },

  // 2. ทีมที่ปรึกษาโครงการ - กลุ่มที่ 1: Legal, Fund & Governance
  {
    id: 'adv-01',
    name: 'ผศ.ดร. มารุต ตั้งวัฒนาชุลีพร',
    nickname: 'ปุ่น',
    roleTitle: 'รองอธิการบดี มหาวิทยาลัยบูรพา / ที่ปรึกษาด้านกฎหมายและระเบียบกองทุน ววน.',
    teamCategory: 'ADVISORY_LEGAL',
    teamCategoryName: '2. ทีมที่ปรึกษา: กลุ่มที่ 1 ด้านกฎหมาย ระเบียบกองทุน ววน. และการกำกับดูแลภาครัฐ',
    organization: 'มหาวิทยาลัยบูรพา',
    expertise: 'ระเบียบ ข้อกำหนด กองทุนการวิจัย และการบริหารองค์กร / การเรียนรู้ตลอดชีวิต',
    strategicFit: 'ผู้นำระดับสูงในสถาบันอุดมศึกษา เข้าใจทั้งมิติการบริหารองค์กรภาครัฐ นโยบาย ววน. และมุมมองของบอร์ด/ผู้บริหารระดับสูง',
    mainResponsibilities: [
      'รีวิวข้อเสนอทางวิชาการ ข้อ 4.3.1',
      'ข้อ 4.3.2 เสนอมุมมองอำนาจและการตัดสินใจของบอร์ด',
      'ข้อ 4.3.3 รีวิวการจัดหมวดหมู่ Fund vs Operation',
      'ข้อ 4.3.4 รีวิวข้อเสนอเชิงนโยบาย Tier Position',
      'รีวิวแบบทดสอบ และ คอนเทนต์ความรู้ระดับบอร์ดและผู้บริหารระดับสูง',
    ],
    specificConsultingTopics: [
      'ขอบเขตอำนาจหน้าที่และการตัดสินใจของคณะกรรมการ กสว. และผู้บริหารระดับสูง สกสว.',
      'ความสมดุลระหว่างการกำกับดูแลกับการบริหารงานขององค์กรในระบบ ววน.',
      'การยกร่างคู่มือปฏิบัติงานสำหรับคณะกรรมการ (ข้อ 4.3.5)',
      'แนวทางการเข้าสัมภาษณ์บอร์ดและผู้บริหารระดับสูง รวมทั้งการร่วมดำเนินการ Focus Group ตาม ข้อ 4.3.2',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-03', 'DEL-04'],
  },
  {
    id: 'adv-02',
    name: 'นายกานต์กุญช์ บำรุงชาติ',
    nickname: 'บอย',
    roleTitle: 'หน.ส่วนบริหารงานวิจัย & IP มหาวิทยาลัยแม่ฟ้าหลวง / ที่ปรึกษาด้านการบริหารงานวิจัย',
    teamCategory: 'ADVISORY_LEGAL',
    teamCategoryName: '2. ทีมที่ปรึกษา: กลุ่มที่ 1 ด้านกฎหมาย ระเบียบกองทุน ววน. และการกำกับดูแลภาครัฐ',
    organization: 'มหาวิทยาลัยแม่ฟ้าหลวง',
    expertise: 'ระเบียบกองทุนวิจัยฯ การดำเนินงานร่วมกับ สกสว. ทรัพย์สินทางปัญญาและนวัตกรรม',
    strategicFit: 'ผู้ปฏิบัติงานจริงในด่านหน้า เข้าใจกระบวนงานขอรับจัดสรรงบประมาณ FF/SF สัญญา การเบิกจ่าย และการนำผลงานวิจัยไปใช้ประโยชน์',
    mainResponsibilities: [
      'ข้อ 4.3.1 รีวิวกฎหมายลำดับรอง FF/SF/PMU',
      'ข้อ 4.3.3 รีวิวระบบงานบริหารกองทุน',
      'ข้อ 4.3.4 รีวิว Gap Analysis งานจริง และข้อเสนอการลงทุน/IP ตาม ม.58',
    ],
    specificConsultingTopics: [
      'จุดติดขัดและภาระงานจริง (Operational Friction) ในการปฏิบัติตามประกาศ กสว. ด้าน FF และ SF',
      'กลไกการบริหารสัญญา การใช้จ่ายเงินของ PMU และการเร่งรัดชดใช้ทุน',
      'แนวทางการบริหารทรัพย์สินทางปัญญาและการร่วมลงทุนนวัตกรรมตามข้อเสนอแนะเชิงนโยบาย',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-04'],
  },
  {
    id: 'adv-03',
    name: 'อ.นภวัฒน์ สืบนุสรณ์',
    nickname: 'มะตูม',
    roleTitle: 'อาจารย์ประจำสำนักวิชานิติศาสตร์ มหาวิทยาลัยแม่ฟ้าหลวง / ที่ปรึกษากฎหมาย',
    teamCategory: 'ADVISORY_LEGAL',
    teamCategoryName: '2. ทีมที่ปรึกษา: กลุ่มที่ 1 ด้านกฎหมาย ระเบียบกองทุน ววน. และการกำกับดูแลภาครัฐ',
    organization: 'มหาวิทยาลัยแม่ฟ้าหลวง',
    expertise: 'กฎหมายกองทุนการวิจัยฯ, กฎหมายหลักประกันทางธุรกิจ, นิติศาสตร์มหาชน',
    strategicFit: 'นักวิชาการนิติศาสตร์ผู้เชี่ยวชาญโครงสร้าง พ.ร.บ. ววน. และกฎหมายลำดับรอง',
    mainResponsibilities: [
      'รีวิวข้อ 4.3.1 (Legal Hierarchy & Inventory 3 ระดับ)',
      'ข้อ 4.3.2 รีวิวการตีความอำนาจ ม.58 อิสระและโปร่งใส',
      'ข้อ 4.3.4 รีวิวรายงานข้อเสนอนโยบาย 3 ฉบับ',
    ],
    specificConsultingTopics: [
      'การจัดทำระบบ Traceability และตรวจสอบลำดับศักดิ์ของ พ.ร.บ. สภานโยบายฯ 2562 (และฉบับ 2 พ.ศ. 2568)',
      'การตีความทางนิติศาสตร์ในประเด็นที่คลุมเครือ และการวิเคราะห์ขอบเขตอำนาจตามมาตรา 58',
      'การสอบทานความถูกต้องของเนื้อหากฎหมายในคู่มือปฏิบัติงาน 2 ฉบับ',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-03'],
  },
  {
    id: 'adv-04',
    name: 'ผศ.ดร.กนกพร ศรีสุจริตพานิช',
    nickname: 'อ.อู๋',
    roleTitle: 'รองคณบดีฝ่ายบริหาร คณะสหเวชศาสตร์ มหาวิทยาลัยบูรพา / ที่ปรึกษาด้านการบริหารทรัพยากรและการเงิน',
    teamCategory: 'ADVISORY_LEGAL',
    teamCategoryName: '2. ทีมที่ปรึกษา: กลุ่มที่ 1 ด้านกฎหมาย ระเบียบกองทุน ววน. และการกำกับดูแลภาครัฐ',
    organization: 'มหาวิทยาลัยบูรพา',
    expertise: 'การบริหารทรัพยากร การเงิน และการพัฒนาบุคลากร (Financial, Resource & Workforce Management)',
    strategicFit: 'ผู้บริหารระดับคณะที่มีความเชี่ยวชาญการบริหารงบประมาณ การเงินพัสดุ และการจัดการกำลังคน',
    mainResponsibilities: [
      'รีวิวเนื้อหาทางวิชาการและระเบียบ ข้อบังคับ ที่เกี่ยวข้อง ตาม 4.3.1 - 4.3.4',
      'รีวิวคอนเทนต์สำหรับผลิตชุดความรู้ แบบทดสอบ และคู่มือการปฏิบัติงาน ทั้ง 2 เล่ม',
    ],
    specificConsultingTopics: [
      'การบริหารการเงินการคลังในสถาบันวิจัยและมหาวิทยาลัย',
      'การเชื่อมโยงระบบพัสดุและระเบียบการเงินกับการปฏิบัติงานจริง',
    ],
    deliverableLinks: ['DEL-01', 'DEL-02', 'DEL-03', 'DEL-04'],
  },

  // 2. ทีมที่ปรึกษาโครงการ - กลุ่มที่ 2: Private Law & Investment
  {
    id: 'adv-05',
    name: 'คุณธนา & คุณเอ๋',
    nickname: 'ธนา & เอ๋',
    roleTitle: 'ที่ปรึกษาด้านกฎหมายภาคเอกชนและการร่วมลงทุน (Private Law & Investment Advisors)',
    teamCategory: 'ADVISORY_PRIVATE',
    teamCategoryName: '2. ทีมที่ปรึกษา: กลุ่มที่ 2 ด้านกฎหมายธุรกิจ การเงินการคลัง และการลงทุนภาคเอกชน',
    organization: 'ที่ปรึกษากฎหมายธุรกิจอิสระ',
    expertise: 'กฎหมายธุรกิจ นิติกรรมสัญญา การร่วมลงทุน (Joint Venture) และกฎหมายการค้า/เอกชน',
    strategicFit: 'ให้มุมมองภายนอก (Private Sector Perspective) ต่อข้อจำกัดทางกฎหมายของภาครัฐในการส่งเสริมนวัตกรรม',
    mainResponsibilities: [
      'รีวิวข้อ 4.3.4 (รายงานข้อเสนอแนะเชิงนโยบายด้านการลงทุน ม.58 / Startup / Spin-off)',
      'ข้อ 4.3.1 (พ.ร.บ. จัดซื้อจัดจ้างฯ และกฎหมายธุรกิจที่เกี่ยวข้อง)',
    ],
    specificConsultingTopics: [
      'รีวิวข้อเสนอและแนวทางเพื่อปลดล็อกข้อจำกัดทางกฎหมายในการที่กองทุน ววน. หรือ สกสว. จะร่วมลงทุนหรือหนุนเสริม Deep Tech / Startup',
      'การออกแบบกลไกบริหารความเสี่ยงทางกฎหมายและธรรมาภิบาลในการร่วมลงทุนกับภาคเอกชน',
      'การเปรียบเทียบโมเดลการลงทุนขององค์กรสนับสนุนนวัตกรรมในต่างประเทศ',
    ],
    deliverableLinks: ['DEL-02', 'DEL-04'],
  },

  // 2. ทีมที่ปรึกษาโครงการ - กลุ่มที่ 3: Learning Design, HRD & Executive Modules
  {
    id: 'adv-06',
    name: 'คุณบัณฑิตา พละพงศ์',
    nickname: 'แอ๋ม',
    roleTitle: 'Head of Learning Academy, KBTG / ที่ปรึกษาด้าน Learning Architecture & HRD',
    teamCategory: 'ADVISORY_HRD',
    teamCategoryName: '2. ทีมที่ปรึกษา: กลุ่มที่ 3 ด้านการออกแบบระบบการเรียนรู้และการพัฒนาบุคลากร',
    organization: 'KBTG (Kasikorn Business-Technology Group)',
    expertise: 'Learning Architecture, HRD, Competency Matrix, Corporate Academy Design',
    strategicFit: 'ผู้นำด้านการสร้างระบบพัฒนาบุคลากรในองค์กรเทคโนโลยีชั้นนำระดับประเทศ',
    mainResponsibilities: [
      'ข้อ 4.3.5 การจัดทำ Knowledge Matrix Framework, โครงสร้างระบบ KM, Learning Journey Design',
      'รับผิดชอบการทำคอนเทนต์สำหรับงานผลิตวิดีโอองค์ความรู้ของระดับบอร์ดและผู้บริหารระดับสูง',
      'การทำอินโฟกราฟิก 8 ชิ้น ร่วมกับคุณสายป่าน',
    ],
    specificConsultingTopics: [
      'การวางโครงสร้าง Legal Competency / Knowledge Matrix ให้สอดคล้องกับพฤติกรรมและความต้องการจริงของคนทำงาน',
      'กลยุทธ์การแปลงเนื้อหาเชิงเทคนิคให้เป็น Learning Modules ที่น่าสนใจและนำไปใช้จริงในที่ทำงาน',
      'แนวทางการจัดทำระบบ KM ของ สกสว. ให้ทันสมัยและยั่งยืน',
    ],
    deliverableLinks: ['DEL-03', 'DEL-04'],
  },
  {
    id: 'adv-07',
    name: 'คุณซัน',
    nickname: 'ซัน',
    roleTitle: 'ที่ปรึกษาด้านการออกแบบโมดูลพัฒนาผู้บริหารทุกระดับ (Executive Development Advisor)',
    teamCategory: 'ADVISORY_HRD',
    teamCategoryName: '2. ทีมที่ปรึกษา: กลุ่มที่ 3 ด้านการออกแบบระบบการเรียนรู้และการพัฒนาบุคลากร',
    organization: 'ที่ปรึกษาพัฒนาภาวะผู้นำอิสระ',
    expertise: 'Executive Development, Leadership Learning Modules, Scenario-based Learning',
    strategicFit: 'ผู้เชี่ยวชาญด้านการพัฒนาผู้บริหารระดับสูง กลาง และต้น',
    mainResponsibilities: [
      'ข้อ 4.3.5 การออกแบบชุดสื่อวิดีโอ 15 คลิป (คลิปความรู้ 6 คลิป, คลิปสั้น 9 คลิป)',
      'การออกแบบแบบทดสอบ 12 ชุด (Scenario-based Assessment)',
    ],
    specificConsultingTopics: [
      'การออกแบบเนื้อหาวิดีโอสั้น 30–60 วินาที และวิดีโอ 3–5 นาที สำหรับผู้บริหารระดับกลาง/ต้น และฝ่ายปฏิบัติการ',
      'การออกแบบข้อสอบแบบประยุกต์ใช้ตามสถานการณ์จริง (Scenario-based Assessment)',
    ],
    deliverableLinks: ['DEL-03', 'DEL-04'],
  },
];

export const mockProject: Project = {
  id: 'proj-tsri-2026-01',
  code: 'TSRI-LEGAL-2026',
  title: 'โครงการศึกษา วิเคราะห์ และพัฒนาองค์ความรู้ด้านกฎหมาย ระเบียบ และแนวปฏิบัติที่เกี่ยวข้องกับการดำเนินงานของ สกสว.',
  description: 'โครงการพัฒนาระบบบริหารความรู้และควบคุมการปฏิบัติตามกฎหมาย นโยบาย ววน. และระเบียบ สกสว. ครบวงจร',
  organization: 'สำนักงานคณะกรรมการส่งเสริมวิทยาศาสตร์ วิจัยและนวัตกรรม (สกสว.)',
  current_gate: 'G1', // G1: Source Verification
  start_date: '2026-01-15',
  end_date: '2026-10-31',
  baseline_budget: 4500000,
  created_at: '2026-01-10T08:00:00Z',
};

export const mockDeliverables: Deliverable[] = [
  {
    id: 'del-01',
    project_id: mockProject.id,
    code: 'DEL-01',
    title: 'รายงานการวิเคราะห์และรวบรวมบทบัญญัติกฎหมาย ระเบียบ และคำสั่งที่เกี่ยวข้องกับ สกสว. (Inception Report)',
    description: 'รวบรวม พ.ร.บ. สภานโยบายฯ พ.ศ. 2562 และระเบียบกองทุน ววน. ครบถ้วน',
    weight_percentage: 20,
    due_date: '2026-03-31',
    gate_milestone: 'G1',
    status: 'APPROVED',
  },
  {
    id: 'del-02',
    project_id: mockProject.id,
    code: 'DEL-02',
    title: 'รายงานการวิเคราะห์ช่องว่าง (Legal & Operational Gap Analysis) และผลกระทบต่อภารกิจ',
    description: 'วิเคราะห์ความสอดคล้องระหว่างอำนาจหน้าที่ตามกฎหมายกับกระบวนการทำงานจริง',
    weight_percentage: 25,
    due_date: '2026-05-31',
    gate_milestone: 'G3',
    status: 'IN_PROGRESS',
  },
  {
    id: 'del-03',
    project_id: mockProject.id,
    code: 'DEL-03',
    title: 'ร่างคู่มือและแนวปฏิบัติการดำเนินงานตามกฎหมายระเบียบใหม่ (Standard Operating Procedure Guide)',
    description: 'จัดทำร่างคู่มือ SOP พร้อม Flowchart สำหรับหน่วยงานภายใน สกสว.',
    weight_percentage: 25,
    due_date: '2026-07-31',
    gate_milestone: 'G4',
    status: 'BACKLOG',
  },
  {
    id: 'del-04',
    project_id: mockProject.id,
    code: 'DEL-04',
    title: 'ชุดองค์ความรู้และระบบ Legal Traceability Explorer ฉบับสมบูรณ์',
    description: 'ระบบสืบค้นความเชื่อมโยงของบทบัญญัติ สิทธิ หน้าที่ และเอกสารหลักฐาน',
    weight_percentage: 30,
    due_date: '2026-09-30',
    gate_milestone: 'G5',
    status: 'BACKLOG',
  },
];

export const mockDocuments: DocumentItem[] = [
  // 01. กฎหมายแม่บท
  {
    id: 'doc-law-001',
    project_id: mockProject.id,
    prefix_code: 'LAW',
    document_code: 'LAW-NSC-001-2562',
    title: 'พ.ร.บ. สภานโยบายการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรมแห่งชาติ พ.ศ. 2562',
    category: '01_กฎหมายแม่บท / 01.01_พระราชบัญญัติสภานโยบาย',
    issuing_body: 'ราชกิจจานุเบกษา',
    effective_date: '2019-05-02',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['พ.ร.บ. สภานโยบาย', 'กฎหมายแม่บท', 'ววน.'],
    is_confidential: false,
    created_at: '2026-01-20T09:00:00Z',
    updated_at: '2026-01-20T09:00:00Z',
    versions: [
      {
        id: 'ver-law-001-1',
        document_id: 'doc-law-001',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'LAW-NSC-001-2562_พ.ร.บ. สภานโยบายการอุดมศึกษาวิทยาศาสตร์วิจัยและนวัตกรรมแห่งชาติ-พ.ศ.-2562.pdf',
        file_size_bytes: 344043,
        file_mime_type: 'application/pdf',
        storage_r2_key: '01_กฎหมายแม่บท/01.01_พระราชบัญญัติสภานโยบาย/LAW-NSC-001-2562_พ.ร.บ. สภานโยบายการอุดมศึกษาวิทยาศาสตร์วิจัยและนวัตกรรมแห่งชาติ-พ.ศ.-2562.pdf',
        storage_url: '/documents/01_กฎหมายแม่บท/01.01_พระราชบัญญัติสภานโยบาย/LAW-NSC-001-2562_พ.ร.บ. สภานโยบายการอุดมศึกษาวิทยาศาสตร์วิจัยและนวัตกรรมแห่งชาติ-พ.ศ.-2562.pdf',
        change_summary: 'ฉบับประกาศราชกิจจานุเบกษา ตรวจสอบเทียบตัวบทสมบูรณ์',
        status: 'VALIDATED',
        validated_at: '2026-01-22T10:00:00Z',
        created_at: '2026-01-20T09:00:00Z',
      },
    ],
  },
  {
    id: 'doc-law-002',
    project_id: mockProject.id,
    prefix_code: 'LAW',
    document_code: 'LAW-NSC-002-2568',
    title: 'พ.ร.บ. สภานโยบายการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรมแห่งชาติ (ฉบับที่ 2) พ.ศ. 2568',
    category: '01_กฎหมายแม่บท / 01.01_พระราชบัญญัติสภานโยบาย',
    issuing_body: 'ราชกิจจานุเบกษา',
    effective_date: '2025-02-15',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['พ.ร.บ. สภานโยบาย', 'ฉบับที่ 2', '2568'],
    is_confidential: false,
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-02-01T09:00:00Z',
    versions: [
      {
        id: 'ver-law-002-1',
        document_id: 'doc-law-002',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'LAW-NSC-002-2568_พ.ร.บ. สภานโยบายการอุดมศึกษาวิทยาศาสตร์วิจัยและนวัตกรรมแห่งชาติ-ฉบับที่-2-พ.ศ.-2568.pdf',
        file_size_bytes: 78049,
        file_mime_type: 'application/pdf',
        storage_r2_key: '01_กฎหมายแม่บท/01.01_พระราชบัญญัติสภานโยบาย/LAW-NSC-002-2568_พ.ร.บ. สภานโยบายการอุดมศึกษาวิทยาศาสตร์วิจัยและนวัตกรรมแห่งชาติ-ฉบับที่-2-พ.ศ.-2568.pdf',
        storage_url: '/documents/01_กฎหมายแม่บท/01.01_พระราชบัญญัติสภานโยบาย/LAW-NSC-002-2568_พ.ร.บ. สภานโยบายการอุดมศึกษาวิทยาศาสตร์วิจัยและนวัตกรรมแห่งชาติ-ฉบับที่-2-พ.ศ.-2568.pdf',
        change_summary: 'ฉบับแก้ไขเพิ่มเติม พ.ศ. 2568 เรื่องการปรับปรุงโครงสร้างบอร์ดและอำนาจ PMU',
        status: 'VALIDATED',
        validated_at: '2026-02-05T10:00:00Z',
        created_at: '2026-02-01T09:00:00Z',
      },
    ],
  },
  {
    id: 'doc-law-003',
    project_id: mockProject.id,
    prefix_code: 'LAW',
    document_code: 'LAW-SRI-001-2562',
    title: 'พระราชบัญญัติการส่งเสริมวิทยาศาสตร์ การวิจัยและนวัตกรรม พ.ศ. 2562',
    category: '01_กฎหมายแม่บท / 01.02_พระราชบัญญัติส่งเสริม-ววน',
    issuing_body: 'ราชกิจจานุเบกษา',
    effective_date: '2019-05-02',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['พ.ร.บ. ส่งเสริม ววน.', 'กองทุน ววน.', 'ม.58'],
    is_confidential: false,
    created_at: '2026-01-20T09:00:00Z',
    updated_at: '2026-01-20T09:00:00Z',
    versions: [
      {
        id: 'ver-law-003-1',
        document_id: 'doc-law-003',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'LAW-SRI-001-2562_พระราชบัญญัติการส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม-พ.ศ.-2562_v0.1.pdf',
        file_size_bytes: 219248,
        file_mime_type: 'application/pdf',
        storage_r2_key: '01_กฎหมายแม่บท/01.02_พระราชบัญญัติส่งเสริม-ววน/LAW-SRI-001-2562_พระราชบัญญัติการส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม-พ.ศ.-2562_v0.1.pdf',
        storage_url: '/documents/01_กฎหมายแม่บท/01.02_พระราชบัญญัติส่งเสริม-ววน/LAW-SRI-001-2562_พระราชบัญญัติการส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม-พ.ศ.-2562_v0.1.pdf',
        change_summary: 'ฉบับแม่บท พ.ร.บ. ววน. บัญญัติอำนาจหน้าที่ กสว., สกสว. และกองทุน ววน.',
        status: 'VALIDATED',
        validated_at: '2026-01-22T10:00:00Z',
        created_at: '2026-01-20T09:00:00Z',
      },
    ],
  },
  {
    id: 'doc-law-004',
    project_id: mockProject.id,
    prefix_code: 'LAW',
    document_code: 'LAW-SRI-002-2568',
    title: 'พระราชบัญญัติการส่งเสริมวิทยาศาสตร์ การวิจัยและนวัตกรรม (ฉบับที่ 2) พ.ศ. 2568',
    category: '01_กฎหมายแม่บท / 01.02_พระราชบัญญัติส่งเสริม-ววน',
    issuing_body: 'ราชกิจจานุเบกษา',
    effective_date: '2025-02-15',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['พ.ร.บ. ส่งเสริม ววน.', 'ฉบับที่ 2', '2568'],
    is_confidential: false,
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-02-01T09:00:00Z',
    versions: [
      {
        id: 'ver-law-004-1',
        document_id: 'doc-law-004',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'LAW-SRI-002-2568_พระราชบัญญัติการส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม-ฉบับที่-2-พ.ศ.-2568_v0.1.pdf',
        file_size_bytes: 76890,
        file_mime_type: 'application/pdf',
        storage_r2_key: '01_กฎหมายแม่บท/01.02_พระราชบัญญัติส่งเสริม-ววน/LAW-SRI-002-2568_พระราชบัญญัติการส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม-ฉบับที่-2-พ.ศ.-2568_v0.1.pdf',
        storage_url: '/documents/01_กฎหมายแม่บท/01.02_พระราชบัญญัติส่งเสริม-ววน/LAW-SRI-002-2568_พระราชบัญญัติการส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม-ฉบับที่-2-พ.ศ.-2568_v0.1.pdf',
        change_summary: 'ฉบับแก้ไขเพิ่มเติมปี 2568',
        status: 'VALIDATED',
        validated_at: '2026-02-05T10:00:00Z',
        created_at: '2026-02-01T09:00:00Z',
      },
    ],
  },

  // 02. กฎหมายลำดับรอง - ระเบียบสภานโยบาย & ระเบียบ กสว.
  {
    id: 'doc-reg-001',
    project_id: mockProject.id,
    prefix_code: 'REG',
    document_code: 'REG-NSC-001-2562',
    title: 'ระเบียบสภานโยบาย ว่าด้วยการบริหารกองทุนส่งเสริมวิทยาศาสตร์ วิจัยและนวัตกรรม พ.ศ. 2562',
    category: '02_กฎหมายลำดับรอง / 02.01_ระเบียบสภานโยบาย',
    issuing_body: 'สภานโยบายฯ',
    effective_date: '2019-11-20',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['ระเบียบสภานโยบาย', 'บริหารกองทุน ววน.'],
    is_confidential: false,
    created_at: '2026-01-25T11:00:00Z',
    updated_at: '2026-01-25T11:00:00Z',
    versions: [
      {
        id: 'ver-reg-001-1',
        document_id: 'doc-reg-001',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'REG-NSC-001-2562_ระเบียบสภานโยบาย-ว่าด้วยการบริหารกองทุนส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม_พ.ศ.-2562_v0.1.pdf.pdf',
        file_size_bytes: 2221023,
        file_mime_type: 'application/pdf',
        storage_r2_key: '02_กฎหมายลำดับรอง/02.01_ระเบียบสภานโยบาย/REG-NSC-001-2562_ระเบียบสภานโยบาย-ว่าด้วยการบริหารกองทุนส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม_พ.ศ.-2562_v0.1.pdf.pdf',
        storage_url: '/documents/02_กฎหมายลำดับรอง/02.01_ระเบียบสภานโยบาย/REG-NSC-001-2562_ระเบียบสภานโยบาย-ว่าด้วยการบริหารกองทุนส่งเสริมวิทยาศาสตร์การวิจัยและนวัตกรรม_พ.ศ.-2562_v0.1.pdf.pdf',
        change_summary: 'ระเบียบหลักว่าด้วยการบริหารเงินกองทุน ววน.',
        status: 'VALIDATED',
        validated_at: '2026-01-25T14:00:00Z',
        created_at: '2026-01-25T11:00:00Z',
      },
    ],
  },
  {
    id: 'doc-reg-002',
    project_id: mockProject.id,
    prefix_code: 'REG',
    document_code: 'REG-PMH-001-2564',
    title: 'ระเบียบ กสว. ว่าด้วยการเร่งรัดและติดตามให้มีการชดใช้เงินคืน พ.ศ. 2564',
    category: '02_กฎหมายลำดับรอง / 02.02_ระเบียบ-กสว',
    issuing_body: 'กสว.',
    effective_date: '2021-04-10',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['ระเบียบ กสว.', 'ชดใช้เงินคืน', 'ติดตามทุน'],
    is_confidential: false,
    created_at: '2026-01-26T10:00:00Z',
    updated_at: '2026-01-26T10:00:00Z',
    versions: [
      {
        id: 'ver-reg-002-1',
        document_id: 'doc-reg-002',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'REG-PMH-001-2564_ระเบียบ-กสว-ว่าด้วยการเร่งรัดและติดตามให้มีการชดใช้เงินคืน_พ.ศ.-2564v0.1.pdf',
        file_size_bytes: 116492,
        file_mime_type: 'application/pdf',
        storage_r2_key: '02_กฎหมายลำดับรอง/02.02_ระเบียบ-กสว/REG-PMH-001-2564_ระเบียบ-กสว-ว่าด้วยการเร่งรัดและติดตามให้มีการชดใช้เงินคืน_พ.ศ.-2564v0.1.pdf',
        storage_url: '/documents/02_กฎหมายลำดับรอง/02.02_ระเบียบ-กสว/REG-PMH-001-2564_ระเบียบ-กสว-ว่าด้วยการเร่งรัดและติดตามให้มีการชดใช้เงินคืน_พ.ศ.-2564v0.1.pdf',
        change_summary: 'หลักเกณฑ์การเร่งรัดติดตามการชดใช้เงินคืนกองทุน',
        status: 'VALIDATED',
        validated_at: '2026-01-28T10:00:00Z',
        created_at: '2026-01-26T10:00:00Z',
      },
    ],
  },
  {
    id: 'doc-reg-003',
    project_id: mockProject.id,
    prefix_code: 'REG',
    document_code: 'REG-PMH-002-2562',
    title: 'ระเบียบ กสว. ว่าด้วยการรับเงิน จ่ายเงิน และเก็บรักษาเงิน พ.ศ. 2562',
    category: '02_กฎหมายลำดับรอง / 02.02_ระเบียบ-กสว',
    issuing_body: 'กสว.',
    effective_date: '2019-12-01',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['ระเบียบ กสว.', 'การเงิน', 'รับเงินจ่ายเงิน'],
    is_confidential: false,
    created_at: '2026-01-26T11:00:00Z',
    updated_at: '2026-01-26T11:00:00Z',
    versions: [
      {
        id: 'ver-reg-003-1',
        document_id: 'doc-reg-003',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'REG-PMH-002-2562_ระเบียบ-กสว-ว่าด้วยการรับเงินจ่ายเงินและเก็บรักษาเงิน_พ.ศ.-2562_v0.1.pdf',
        file_size_bytes: 401681,
        file_mime_type: 'application/pdf',
        storage_r2_key: '02_กฎหมายลำดับรอง/02.02_ระเบียบ-กสว/REG-PMH-002-2562_ระเบียบ-กสว-ว่าด้วยการรับเงินจ่ายเงินและเก็บรักษาเงิน_พ.ศ.-2562_v0.1.pdf',
        storage_url: '/documents/02_กฎหมายลำดับรอง/02.02_ระเบียบ-กสว/REG-PMH-002-2562_ระเบียบ-กสว-ว่าด้วยการรับเงินจ่ายเงินและเก็บรักษาเงิน_พ.ศ.-2562_v0.1.pdf',
        change_summary: 'ระเบียบการเงินการจ่ายเงินของกองทุน ววน.',
        status: 'VALIDATED',
        validated_at: '2026-01-28T11:00:00Z',
        created_at: '2026-01-26T11:00:00Z',
      },
    ],
  },

  // 02.03 ประกาศ กสว. (ตัวอย่างชุดประกาศสำคัญ)
  {
    id: 'doc-ann-002',
    project_id: mockProject.id,
    prefix_code: 'ANN',
    document_code: 'ANN-PMH-002-2566',
    title: 'ประกาศ กสว. เรื่อง การจัดทำคำของบประมาณด้านการวิจัยและนวัตกรรม พ.ศ. 2566',
    category: '02_กฎหมายลำดับรอง / 02.03_ประกาศ-กสว',
    issuing_body: 'กสว.',
    effective_date: '2023-08-15',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['ประกาศ กสว.', 'คำของบประมาณ', 'FF', 'SF'],
    is_confidential: false,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
    versions: [
      {
        id: 'ver-ann-002-1',
        document_id: 'doc-ann-002',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'ANN-PMH-002-2566_ประกาศ-กสว-เรื่องการจัดทำคำของบประมาณด้านการวิจัยและนวัตกรรม_พ.ศ.-2566.pdf',
        file_size_bytes: 5980249,
        file_mime_type: 'application/pdf',
        storage_r2_key: '02_กฎหมายลำดับรอง/02.03_ประกาศ-กสว/ANN-PMH-002-2566_ประกาศ-กสว-เรื่องการจัดทำคำของบประมาณด้านการวิจัยและนวัตกรรม_พ.ศ.-2566.pdf',
        storage_url: '/documents/02_กฎหมายลำดับรอง/02.03_ประกาศ-กสว/ANN-PMH-002-2566_ประกาศ-กสว-เรื่องการจัดทำคำของบประมาณด้านการวิจัยและนวัตกรรม_พ.ศ.-2566.pdf',
        change_summary: 'เกณฑ์และแนวปฏิบัติการจัดทำคำของบประมาณวิจัย',
        status: 'VALIDATED',
        validated_at: '2026-02-05T10:00:00Z',
        created_at: '2026-02-01T10:00:00Z',
      },
    ],
  },
  {
    id: 'doc-ann-008',
    project_id: mockProject.id,
    prefix_code: 'ANN',
    document_code: 'ANN-PMH-008-2565',
    title: 'ประกาศ กสว. เรื่อง การใช้จ่ายเงินอุดหนุนของหน่วยบริหารและจัดการทุน (PMU) พ.ศ. 2565',
    category: '02_กฎหมายลำดับรอง / 02.03_ประกาศ-กสว',
    issuing_body: 'กสว.',
    effective_date: '2022-09-01',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['ประกาศ กสว.', 'PMU', 'เงินอุดหนุน'],
    is_confidential: false,
    created_at: '2026-02-01T11:00:00Z',
    updated_at: '2026-02-01T11:00:00Z',
    versions: [
      {
        id: 'ver-ann-008-1',
        document_id: 'doc-ann-008',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'ANN-PMH-008-2565_ประกาศ-กสว-เรื่องการใช้จ่ายเงินอุดหนุนของ-PMU_พ.ศ.-2565.pdf',
        file_size_bytes: 1850166,
        file_mime_type: 'application/pdf',
        storage_r2_key: '02_กฎหมายลำดับรอง/02.03_ประกาศ-กสว/ANN-PMH-008-2565_ประกาศ-กสว-เรื่องการใช้จ่ายเงินอุดหนุนของ-PMU_พ.ศ.-2565.pdf',
        storage_url: '/documents/02_กฎหมายลำดับรอง/02.03_ประกาศ-กสว/ANN-PMH-008-2565_ประกาศ-กสว-เรื่องการใช้จ่ายเงินอุดหนุนของ-PMU_พ.ศ.-2565.pdf',
        change_summary: 'หลักเกณฑ์การใช้จ่ายเงินอุดหนุนของ PMU ทั้งหมด',
        status: 'VALIDATED',
        validated_at: '2026-02-05T11:00:00Z',
        created_at: '2026-02-01T11:00:00Z',
      },
    ],
  },
  {
    id: 'doc-ann-013',
    project_id: mockProject.id,
    prefix_code: 'ANN',
    document_code: 'ANN-PMH-013-2564',
    title: 'ประกาศ กสว. เรื่อง มาตรการสนับสนุนทุนสำหรับภาคเอกชนเพื่อส่งเสริมนวัตกรรม (TBIR) พ.ศ. 2564',
    category: '02_กฎหมายลำดับรอง / 02.03_ประกาศ-กสว',
    issuing_body: 'กสว.',
    effective_date: '2021-12-15',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['ประกาศ กสว.', 'TBIR', 'ภาคเอกชน', 'ร่วมลงทุน'],
    is_confidential: false,
    created_at: '2026-02-02T10:00:00Z',
    updated_at: '2026-02-02T10:00:00Z',
    versions: [
      {
        id: 'ver-ann-013-1',
        document_id: 'doc-ann-013',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'ANN-PMH-013-2564_ประกาศ-กสว-เรื่องมาตรการสนับสนุนทุนสำหรับภาคเอกชน-TBIR_พ.ศ.-2564.pdf',
        file_size_bytes: 1680655,
        file_mime_type: 'application/pdf',
        storage_r2_key: '02_กฎหมายลำดับรอง/02.03_ประกาศ-กสว/ANN-PMH-013-2564_ประกาศ-กสว-เรื่องมาตรการสนับสนุนทุนสำหรับภาคเอกชน-TBIR_พ.ศ.-2564.pdf',
        storage_url: '/documents/02_กฎหมายลำดับรอง/02.03_ประกาศ-กสว/ANN-PMH-013-2564_ประกาศ-กสว-เรื่องมาตรการสนับสนุนทุนสำหรับภาคเอกชน-TBIR_พ.ศ.-2564.pdf',
        change_summary: 'มาตรการสนับสนุนทุนสำหรับภาคเอกชน TBIR',
        status: 'VALIDATED',
        validated_at: '2026-02-05T10:00:00Z',
        created_at: '2026-02-02T10:00:00Z',
      },
    ],
  },
  {
    id: 'doc-ord-001',
    project_id: mockProject.id,
    prefix_code: 'ORD',
    document_code: 'ORD-TSRI-001-2569',
    title: 'คำสั่ง สกสว. ที่ บค 7/2569 เรื่อง แต่งตั้งบุคคลตามโครงสร้างตำแหน่ง พ.ศ. 2569',
    category: '02_กฎหมายลำดับรอง / 02.06_คำสั่ง',
    issuing_body: 'สกสว.',
    effective_date: '2026-01-10',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['คำสั่ง สกสว.', 'โครงสร้างตำแหน่ง', 'บุคคล'],
    is_confidential: false,
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-01-15T09:00:00Z',
    versions: [
      {
        id: 'ver-ord-001-1',
        document_id: 'doc-ord-001',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'ORD-TSRI-001-2569_คำสั่ง-สกสว-ที่-บค-7-2569-เรื่องแต่งตั้งบุคคลตามโครงสร้างตำแหน่ง-พ.ศ.-2569.pdf',
        file_size_bytes: 7780482,
        file_mime_type: 'application/pdf',
        storage_r2_key: '02_กฎหมายลำดับรอง/02.06_คำสั่ง/ORD-TSRI-001-2569_คำสั่ง-สกสว-ที่-บค-7-2569-เรื่องแต่งตั้งบุคคลตามโครงสร้างตำแหน่ง-พ.ศ.-2569.pdf',
        storage_url: '/documents/02_กฎหมายลำดับรอง/02.06_คำสั่ง/ORD-TSRI-001-2569_คำสั่ง-สกสว-ที่-บค-7-2569-เรื่องแต่งตั้งบุคคลตามโครงสร้างตำแหน่ง-พ.ศ.-2569.pdf',
        change_summary: 'คำสั่งแต่งตั้งบุคคลตามโครงสร้าง สกสว.',
        status: 'VALIDATED',
        validated_at: '2026-01-18T10:00:00Z',
        created_at: '2026-01-15T09:00:00Z',
      },
    ],
  },
  {
    id: 'doc-tor-001',
    project_id: mockProject.id,
    prefix_code: 'TOR',
    document_code: 'TOR-TSRI-2569-01',
    title: 'เอกสารข้อกำหนดของโครงการ (Terms of Reference: TOR) ฉบับลงนามอนุมัติ',
    category: '00_บริหารและควบคุมโครงการ / 00.01_TOR-สัญญา',
    issuing_body: 'สกสว.',
    effective_date: '2026-01-15',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['TOR', 'สัญญางาน', 'Baseline', '4.3.1-4.3.5'],
    is_confidential: true,
    created_at: '2026-01-15T08:30:00Z',
    updated_at: '2026-01-15T08:30:00Z',
    versions: [
      {
        id: 'ver-tor-001-1',
        document_id: 'doc-tor-001',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'TOR_TSRI_Legal_Research_Project_Final.pdf',
        file_size_bytes: 4200000,
        file_mime_type: 'application/pdf',
        storage_r2_key: '00_บริหารและควบคุมโครงการ/00.01_TOR-สัญญา/TOR_TSRI_Legal_Research_Project_Final.pdf',
        storage_url: '/documents/00_บริหารและควบคุมโครงการ/00.01_TOR-สัญญา/TOR_TSRI_Legal_Research_Project_Final.pdf',
        change_summary: 'ฉบับลงนามในสัญญาจ้างโครงการ',
        status: 'VALIDATED',
        validated_at: '2026-01-15T10:00:00Z',
        created_at: '2026-01-15T08:30:00Z',
      },
    ],
  },
  {
    id: 'doc-mom-001',
    project_id: mockProject.id,
    prefix_code: 'MOM',
    document_code: 'MOM-2026-01',
    title: 'รายงานการประชุม Kick-off โครงการศึกษา วิเคราะห์ และพัฒนาองค์ความรู้ด้านกฎหมาย ครั้งที่ 1/2569',
    category: '00_บริหารและควบคุมโครงการ / 00.04_บันทึกการประชุม-MOM',
    issuing_body: 'คณะทำงานโครงการ',
    status: 'VALIDATED',
    latest_version_number: '1.0',
    tags: ['Kick-off', 'MOM', 'คณะทำงาน', '3 ทีม'],
    is_confidential: false,
    created_at: '2026-09-18T18:30:00Z',
    updated_at: '2026-09-18T18:30:00Z',
    versions: [
      {
        id: 'ver-mom-001-1',
        document_id: 'doc-mom-001',
        project_id: mockProject.id,
        version_number: '1.0',
        file_name: 'MOM_Kickoff_01_2569.pdf',
        file_size_bytes: 1450000,
        file_mime_type: 'application/pdf',
        storage_r2_key: '00_บริหารและควบคุมโครงการ/00.04_บันทึกการประชุม-MOM/MOM_Kickoff_01_2569.pdf',
        storage_url: '/documents/00_บริหารและควบคุมโครงการ/00.04_บันทึกการประชุม-MOM/MOM_Kickoff_01_2569.pdf',
        change_summary: 'บันทึกการประชุม Kick-off แบ่งโครงสร้าง 3 ทีมและมอบหมายภารกิจที่ปรึกษา',
        status: 'VALIDATED',
        validated_at: '2026-09-18T19:00:00Z',
        created_at: '2026-09-18T18:30:00Z',
      },
    ],
  },
];


export const mockMeetings: MeetingItem[] = [
  {
    id: 'meet-001',
    project_id: mockProject.id,
    meeting_number: 'MTG-2026-01',
    title: 'การประชุม Kick-off โครงการศึกษา วิเคราะห์ และพัฒนาองค์ความรู้ด้านกฎหมาย ระเบียบ และแนวปฏิบัติ สกสว.',
    agenda: '1. ชี้แจงภาพรวม วัตถุประสงค์ และขอบเขตของโครงการ\n2. หารือและกำหนดบทบาทความรับผิดชอบของคณะทำงานและผู้เชี่ยวชาญแต่ละด้าน (3 ทีม)\n3. กำหนดกรอบการดำเนินงานและระยะเวลาการทำงานในแต่ละช่วงของโครงการ',
    meeting_type: 'Kick-off Meeting',
    gate_ref: 'G0',
    scheduled_at: '2026-09-18T17:00:00Z',
    duration_minutes: 90,
    location_or_link: 'การประชุมออนไลน์ผ่านระบบ Zoom',
    status: 'COMPLETED',
    mom_document_version_id: 'ver-005-1',
    attendees_count: 14,
  },
  {
    id: 'meet-002',
    project_id: mockProject.id,
    meeting_number: 'MTG-2026-02',
    title: 'ประชุมพิจารณาร่าง Legal Inventory & Framework ร่วมกับทีมที่ปรึกษาด้านกฎหมายและ HRD',
    agenda: '1. ตรวจสอบความถูกต้องและลำดับศักดิ์ของกฎหมาย 3 ระดับ\n2. วางกรอบ Knowledge Matrix Framework\n3. นัดหมายและเตรียมประเด็นสัมภาษณ์เชิงลึก/Focus Group',
    meeting_type: 'คณะทำงาน & ที่ปรึกษา',
    gate_ref: 'G1',
    scheduled_at: '2026-09-25T14:00:00Z',
    duration_minutes: 120,
    location_or_link: 'ห้องประชุม 501 สกสว. และ Zoom Cloud Meeting',
    status: 'SCHEDULED',
    attendees_count: 12,
  },
];

export const mockActivities: ActivityLogItem[] = [
  {
    id: 'act-001',
    project_id: mockProject.id,
    actor_name: 'นายอนุสรณ์ หนองนา (เด่น) [Super Admin]',
    action: 'SET_SUPER_ADMIN',
    entity_table: 'profiles',
    entity_id: 'usr-super-admin-01',
    description: 'กำหนดสิทธิ์ Super Admin ให้แก่นายอนุสรณ์ หนองนา (dencapvision@gmail.com)',
    created_at: '2026-09-22T02:42:00Z',
  },
  {
    id: 'act-002',
    project_id: mockProject.id,
    actor_name: 'ดร.หนึ่งนิดา สารศรี (ต้นหลิว)',
    action: 'UPLOAD_MOM',
    entity_table: 'documents',
    entity_id: 'doc-005',
    description: 'บันทึกรายงานการประชุม Kick-off ครั้งที่ 1/2569 (MOM-2026-01)',
    created_at: '2026-09-18T18:30:00Z',
  },
  {
    id: 'act-003',
    project_id: mockProject.id,
    actor_name: 'คุณไกรพุฒิ อินทรโยธา (ไนท์)',
    action: 'CONFIRM_BASELINE',
    entity_table: 'projects',
    entity_id: mockProject.id,
    description: 'ยืนยันกรอบขอบเขตการทำงานร่วมกับ สกสว. และมอบหมายภารกิจทีมที่ปรึกษา',
    created_at: '2026-09-18T17:30:00Z',
  },
];

export const mockDashboardData: ExecutiveDashboardData = {
  project: mockProject,
  currentGate: 'G1',
  torCoveragePercentage: 25,
  deliverablesProgress: {
    total: 4,
    completed: 1,
    inProgress: 1,
    pendingReview: 2,
  },
  pendingReviewsCount: 2,
  evidenceGapCount: 1,
  upcomingMeetings: mockMeetings,
  openRisksCount: 1,
  openDecisionsCount: 3,
  myActionItems: [
    {
      id: 'act-1',
      title: 'จัดส่งร่าง Legal Inventory ให้ทีมที่ปรึกษากฎหมายตรวจสอบ (ช่วง 18–25 ก.ย. 69)',
      type: 'TASK',
      due_date: '2026-09-25',
      priority: 'HIGH',
    },
    {
      id: 'act-2',
      title: 'เตรียมชุดคำถามสัมภาษณ์เชิงลึกระดับบอร์ดร่วมกับ ผศ.ดร.มารุต และ ดร.หนึ่งนิดา',
      type: 'REVIEW',
      due_date: '2026-09-28',
      priority: 'HIGH',
    },
    {
      id: 'act-3',
      title: 'ยกร่าง Knowledge Matrix Framework ร่วมกับคุณแอ๋ม (KBTG) และคุณซัน',
      type: 'TASK',
      due_date: '2026-10-02',
      priority: 'MEDIUM',
    },
  ],
  recentDocuments: mockDocuments,
  recentActivities: mockActivities,
};

// -----------------------------------------------------------------------------
// EXPERT REVIEW CENTER BATCH 1 DATA
// -----------------------------------------------------------------------------

export const mockReviewBatches: ReviewBatch[] = [
  {
    id: 'batch-01',
    project_id: mockProject.id,
    batch_number: 'BATCH-01',
    title: 'ชุดตรวจทานที่ 1: การจัดหมวดหมู่กฎหมาย ลำดับศักดิ์ และอำนาจหน้าที่ตาม พ.ร.บ. ววน. และกองทุน ววน.',
    description: 'การกลั่นกรองและรับรองความถูกต้องของบทบัญญัติกฎหมายหลัก 3 ระดับ อำนาจมาตรา 58 และระเบียบกองทุน ววน. เพื่อปลดล็อก Gate G2 (Research Validation)',
    gate_target: 'G2',
    status: 'IN_REVIEW',
    total_items: 4,
    validated_items: 1,
    created_at: '2026-09-19T08:00:00Z',
    updated_at: '2026-09-22T15:30:00Z',
  },
  {
    id: 'batch-02',
    project_id: mockProject.id,
    batch_number: 'BATCH-02',
    title: 'ชุดตรวจทานที่ 2: ร่างรายงาน Gap Analysis ข้อ 4.3.2 และการวิเคราะห์ขอบเขตอำนาจบริหาร',
    description: 'การตรวจสอบความสอดคล้องระหว่างผลการสัมภาษณ์ผู้บริหาร/บอร์ด กับกฎหมายและระเบียบปฏิบัติจริง',
    gate_target: 'G3',
    status: 'OPEN',
    total_items: 3,
    validated_items: 0,
    created_at: '2026-09-22T10:00:00Z',
    updated_at: '2026-09-22T10:00:00Z',
  },
];

export const mockReviewItems: ReviewItem[] = [
  {
    id: 'rev-item-01',
    batch_id: 'batch-01',
    project_id: mockProject.id,
    item_code: 'REV-B1-001',
    title: 'ขอบเขตอำนาจหน้าที่และการตัดสินใจของคณะกรรมการ กสว. และผู้บริหาร สกสว. ตามมาตรา 58',
    document_id: 'doc-001',
    document_code: 'LAW-001',
    document_title: 'พ.ร.บ. การส่งเสริมวิทยาศาสตร์ วิจัยและนวัตกรรม พ.ศ. 2562',
    document_version_number: '1.0',
    deliverable_code: 'DEL-01',
    article_section: 'มาตรา 58 วรรคหนึ่ง และวรรคสอง',
    page_number: 14,
    issue_description: 'ตรวจสอบความชัดเจนของอำนาจ กสว. ในการอนุมัติการร่วมลงทุน (Joint Venture / Spin-off) เทียบกับข้อบังคับการบริหารกองทุน ววน. ว่าต้องได้รับความเห็นชอบจากสภานโยบายฯ หรือไม่',
    assigned_expert_id: 'adv-01',
    assigned_expert_name: 'ผศ.ดร. มารุต ตั้งวัฒนาชุลีพร',
    assigned_category: 'ADVISORY_LEGAL',
    status: 'VALIDATED',
    priority: 'HIGH',
    due_date: '2026-09-24',
    evidence_records: [
      {
        id: 'evd-001',
        review_item_id: 'rev-item-01',
        project_id: mockProject.id,
        reviewer_id: 'adv-01',
        reviewer_name: 'ผศ.ดร. มารุต ตั้งวัฒนาชุลีพร',
        reviewer_role: 'รองอธิการบดี ม.บูรพา / ที่ปรึกษากฎหมายและระเบียบกองทุน ววน.',
        review_date: '2026-09-22T14:30:00Z',
        doc_id_ref: 'LAW-001 v1.0',
        article_section: 'มาตรา 58 วรรคหนึ่ง และวรรคสอง',
        page_number: 14,
        edition_used: 'ราชกิจจานุเบกษา เล่ม 136 ตอนที่ 59 ก หน้า 14 ลงวันที่ 1 พ.ค. 2562',
        rationale: 'มาตรา 58 บัญญัติให้อำนาจ กสว. กำหนดหลักเกณฑ์การร่วมลงทุนและการถือหุ้นในนิติบุคคลเพื่อประโยชน์ในการส่งเสริมนวัตกรรมได้โดยตรง ทั้งนี้ต้องสอดคล้องกับกรอบนโยบาย ววน. ที่สภานโยบายฯ กำหนด',
        requirement_impact: 'ยืนยันโครงสร้างอำนาจใน Inception Report (DEL-01) และส่งผลให้สามารถยกร่างแนวปฏิบัติข้อ 4.3.5 ได้อย่างถูกต้องตามกฎหมาย',
        storage_r2_key: 'evidence/2026/09/EVD_Marut_Sec58_Analysis.pdf',
        evidence_file_name: 'EVD_Marut_Sec58_Analysis.pdf',
        evidence_file_size: 1450000,
        resulting_status: 'VALIDATED',
        created_at: '2026-09-22T14:30:00Z',
      },
    ],
    created_at: '2026-09-19T09:00:00Z',
    updated_at: '2026-09-22T14:30:00Z',
  },
  {
    id: 'rev-item-02',
    batch_id: 'batch-01',
    project_id: mockProject.id,
    item_code: 'REV-B1-002',
    title: 'ข้อติดขัดการเบิกจ่ายงบประมาณ Fundamental Fund (FF) และ Strategic Fund (SF)',
    document_id: 'doc-002',
    document_code: 'REG-004',
    document_title: 'ระเบียบคณะกรรมการส่งเสริม ววน. ว่าด้วยการบริหารเงินกองทุนส่งเสริม ววน. พ.ศ. 2563',
    document_version_number: '1.1',
    deliverable_code: 'DEL-02',
    article_section: 'ข้อ 14 (1) และ ข้อ 18',
    page_number: 8,
    issue_description: 'พบประเด็น Operational Friction และความคลุมเครือในการส่งคืนเงินเหลือจ่ายข้ามปีงบประมาณของหน่วยรับงบประมาณ (PMU / มหาวิทยาลัย)',
    assigned_expert_id: 'adv-02',
    assigned_expert_name: 'นายกานต์กุญช์ บำรุงชาติ',
    assigned_category: 'ADVISORY_LEGAL',
    status: 'SOURCE_CONFLICT',
    priority: 'HIGH',
    due_date: '2026-09-25',
    evidence_records: [
      {
        id: 'evd-002',
        review_item_id: 'rev-item-02',
        project_id: mockProject.id,
        reviewer_id: 'adv-02',
        reviewer_name: 'นายกานต์กุญช์ บำรุงชาติ',
        reviewer_role: 'หน.ส่วนบริหารงานวิจัย & IP ม.แม่ฟ้าหลวง',
        review_date: '2026-09-21T11:15:00Z',
        doc_id_ref: 'REG-004 v1.1',
        article_section: 'ข้อ 14 (1) และ ข้อ 18',
        page_number: 8,
        edition_used: 'ระเบียบ กสว. 2563 ฉบับแก้ไขเพิ่มเติมปี 2565',
        rationale: 'เกิดความขัดแย้งระหว่างแนวปฏิบัติของกรมบัญชีกลางกับข้อ 18 ของระเบียบ กสว. ทำให้มหาวิทยาลัยไม่สามารถกันเงินไว้เบิกจ่ายข้ามปีได้อย่างคล่องตัว จำเป็นต้องจัดทำข้อเสนอเชิงนโยบายเพื่อปลดล็อก',
        requirement_impact: 'กระทบต่อการจัดทำรายงาน Gap Analysis (ข้อ 4.3.2) และต้องเพิ่มเป็นประเด็นหลักในรายงานข้อเสนอแนะเชิงนโยบายชุดที่ 2 (DEL-02)',
        storage_r2_key: 'evidence/2026/09/EVD_Boy_FF_SF_Conflict_Memo.pdf',
        evidence_file_name: 'EVD_Boy_FF_SF_Conflict_Memo.pdf',
        evidence_file_size: 2120000,
        resulting_status: 'SOURCE_CONFLICT',
        created_at: '2026-09-21T11:15:00Z',
      },
    ],
    created_at: '2026-09-19T09:00:00Z',
    updated_at: '2026-09-21T11:15:00Z',
  },
  {
    id: 'rev-item-03',
    batch_id: 'batch-01',
    project_id: mockProject.id,
    item_code: 'REV-B1-003',
    title: 'การสอบทานลำดับศักดิ์ พ.ร.บ. สภานโยบายฯ 2562 และ พ.ร.บ. (ฉบับที่ 2) พ.ศ. 2568',
    document_id: 'doc-001',
    document_code: 'LAW-002',
    document_title: 'พ.ร.บ. สภานโยบายการอุดมศึกษา วิทยาศาสตร์ วิจัยและนวัตกรรมแห่งชาติ (ฉบับที่ 2) พ.ศ. 2568',
    document_version_number: '1.0',
    deliverable_code: 'DEL-01',
    article_section: 'มาตรา 19/1 และ มาตรา 24',
    page_number: 6,
    issue_description: 'ตรวจสอบบทบัญญัติที่มีการแก้ไขเพิ่มเติมปี 2568 เกี่ยวกับอำนาจการกำกับดูแลหน่วยบริหารและจัดการทุน (PMU) และการปรับปรุงโครงสร้างบอร์ด',
    assigned_expert_id: 'adv-03',
    assigned_expert_name: 'อ.นภวัฒน์ สืบนุสรณ์',
    assigned_category: 'ADVISORY_LEGAL',
    status: 'EXPERT_VALIDATION_REQUIRED',
    priority: 'HIGH',
    due_date: '2026-09-26',
    evidence_records: [],
    created_at: '2026-09-19T09:00:00Z',
    updated_at: '2026-09-19T09:00:00Z',
  },
  {
    id: 'rev-item-04',
    batch_id: 'batch-01',
    project_id: mockProject.id,
    item_code: 'REV-B1-004',
    title: 'การเชื่อมโยงระบบพัสดุและระเบียบการเงินกับการปฏิบัติงานจริงในสถาบันวิจัย',
    document_id: 'doc-002',
    document_code: 'REG-008',
    document_title: 'ข้อบังคับ สกสว. ว่าด้วยการเงิน การพัสดุ และการตรวจจ่ายเงิน พ.ศ. 2563',
    document_version_number: '1.0',
    deliverable_code: 'DEL-03',
    article_section: 'หมวด 4 การจัดหาพัสดุวิจัย ข้อ 32–40',
    page_number: 22,
    issue_description: 'ตรวจสอบว่าเกณฑ์การจัดซื้อพัสดุเพื่องานวิจัยและนวัตกรรม สอดคล้องกับ พ.ร.บ. การจัดซื้อจัดจ้างฯ พ.ศ. 2560 หรือมีข้อยกเว้นเฉพาะของกองทุน ววน.',
    assigned_expert_id: 'adv-04',
    assigned_expert_name: 'ผศ.ดร.กนกพร ศรีสุจริตพานิช',
    assigned_category: 'ADVISORY_LEGAL',
    status: 'SOURCE_NOT_VERIFIED',
    priority: 'MEDIUM',
    due_date: '2026-09-28',
    evidence_records: [],
    created_at: '2026-09-19T09:00:00Z',
    updated_at: '2026-09-19T09:00:00Z',
  },
];

